In [20]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [3]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q1 What version of Pandas did you install?

In [4]:
pd.__version__

'3.0.6'

Q2 Records count
How many records are in the dataset?

In [5]:
print(f'the total number of records in the dataset is {len(df)}')

the total number of records in the dataset is 10000

Q3 Fuel types

In [6]:
print(f'there are {df['fuel_type'].nunique()} fuel types in the dataset')

there are 3 fuel types in the dataset

Q4 Missing values - How many columns in the dataset have missing values?

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Q5 Max fuel efficiency - What's the maximum fuel efficiency of cars from Asia?

In [8]:
df_asia = df[df['origin'] == 'Asia']

In [15]:
print(f' the maximum fuel efficiency in Asia is {df_asia["fuel_efficiency_mpg"].max()}')

 the maximum fuel efficiency in Asia is 41.2

Q5 Median value of horsepower Find the median value of the horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.

In [10]:
df['horsepower'].median()

np.float64(254.0)

In [11]:
df['horsepower'].value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [12]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [13]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [14]:
df['horsepower'].median()

np.float64(252.0)

Q7 Sum of weights

Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?

In [ ]:
# Select all the cars from Asia
# Select only columns vehicle_weight and model_year
# Select the first 7 values

df_filtered = df_asia[['vehicle_weight','model_year']].head(7)
df_filtered.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [ ]:
# Get the underlying NumPy array. Let's call it X

X = df_filtered.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [ ]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [ ]:
# Invert XTX.

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [ ]:
# Create an array 

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [ ]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = XTX_inv @ X.T @ y

In [ ]:
# What's the sum of all the elements of the result?
print(f'the sum of all the elements of the result is {w.sum().round(4)}')

the sum of all the elements of the result is 0.3692